// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuffyAmiYumi.Data;

namespace PuffyAmiYumi.Migrations.YumiDb
{
    [DbContext(typeof(YumiDbContext))]
    [Migration("20180718180519_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PuffyAmiYumi.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CheckedOut");

                    b.Property<string>("UserTag");

                    b.HasKey("ID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("PuffyAmiYumi.Models.CartItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartID");

                    b.Property<int?>("ProductID");

                    b.Property<bool>("Purchased");

                    b.HasKey("ID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("PuffyAmiYumi.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductName");

                    b.Property<string>("SKU");

                    b.Property<int>("Stock");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new { ID = 1, ImageURL = "asset/Patchouli.jpg", Price = 11.99m, ProductName = "Karma-Patchouli-Potpourri", Stock = 100 },
                        new { ID = 2, ImageURL = "asset/RoseScented.jpg", Price = 11.99m, ProductName = "Karma-Rose-Potpourri", Stock = 100 },
                        new { ID = 3, ImageURL = "asset/VanillaScented.jpg", Price = 11.99m, ProductName = "Karma-Vanilla-Potpourri", Stock = 100 },
                        new { ID = 4, ImageURL = "asset/JasmineScented.jpg", Price = 11.99m, ProductName = "Karma-Jasmine-Potpourri", Stock = 100 },
                        new { ID = 5, ImageURL = "asset/Sandalwood.jpg", Price = 11.99m, ProductName = "Karma-Sandalwood-Potpourri", Stock = 100 },
                        new { ID = 6, ImageURL = "asset/Lavender.jpg", Price = 11.99m, ProductName = "Karma-Lavender-Potpourri", Stock = 100 },
                        new { ID = 7, ImageURL = "asset/SandalwoodSpice.jpg", Price = 12.99m, ProductName = "Esscents-Sandalwood-Spice-Potpourri", Stock = 100 },
                        new { ID = 8, ImageURL = "asset/Geranium.jpg", Price = 12.99m, ProductName = "Esscents-Geranium-Potpourri", Stock = 100 },
                        new { ID = 9, ImageURL = "asset/MorningBlossom.jpg", Price = 12.99m, ProductName = "Esscents-Morning-Blossom-Potpourri", Stock = 100 },
                        new { ID = 10, ImageURL = "asset/JasmineTea.jpg", Price = 12.99m, ProductName = "Esscents-Jasmine-Tea-Potpourri", Stock = 100 }
                    );
                });

            modelBuilder.Entity("PuffyAmiYumi.Models.CartItem", b =>
                {
                    b.HasOne("PuffyAmiYumi.Models.Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PuffyAmiYumi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });
#pragma warning restore 612, 618
        }
    }
}
