// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuffyAmiYumi.Data;

namespace PuffyAmiYumi.Migrations
{
    [DbContext(typeof(YumiDbContext))]
    [Migration("20180710232523_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PuffyAmiYumi.Model.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL");

                    b.Property<decimal>("Price");

                    b.Property<string>("ProductName");

                    b.Property<int>("Stock");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new { ID = 1, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 2, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 3, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 4, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 5, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 6, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 7, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 8, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 9, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 },
                        new { ID = 10, ImageURL = "", Price = 0m, ProductName = "", Stock = 0 }
                    );
                });

            modelBuilder.Entity("PuffyAmiYumi.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
